// Generated by gencpp from file microstrain_mips/SetAccelNoise.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETACCELNOISE_H
#define MICROSTRAIN_MIPS_MESSAGE_SETACCELNOISE_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetAccelNoiseRequest.h>
#include <microstrain_mips/SetAccelNoiseResponse.h>


namespace microstrain_mips
{

struct SetAccelNoise
{

typedef SetAccelNoiseRequest Request;
typedef SetAccelNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAccelNoise
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetAccelNoise > {
  static const char* value()
  {
    return "6a73c0e939ba0cee17d40a2e3a5f667f";
  }

  static const char* value(const ::microstrain_mips::SetAccelNoise&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetAccelNoise > {
  static const char* value()
  {
    return "microstrain_mips/SetAccelNoise";
  }

  static const char* value(const ::microstrain_mips::SetAccelNoise&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetAccelNoiseRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetAccelNoise >
template<>
struct MD5Sum< ::microstrain_mips::SetAccelNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetAccelNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetAccelNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetAccelNoiseRequest> should match
// service_traits::DataType< ::microstrain_mips::SetAccelNoise >
template<>
struct DataType< ::microstrain_mips::SetAccelNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetAccelNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetAccelNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetAccelNoiseResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetAccelNoise >
template<>
struct MD5Sum< ::microstrain_mips::SetAccelNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetAccelNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetAccelNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetAccelNoiseResponse> should match
// service_traits::DataType< ::microstrain_mips::SetAccelNoise >
template<>
struct DataType< ::microstrain_mips::SetAccelNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetAccelNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetAccelNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETACCELNOISE_H
