// Generated by gencpp from file microstrain_mips/SetAccelBias.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETACCELBIAS_H
#define MICROSTRAIN_MIPS_MESSAGE_SETACCELBIAS_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetAccelBiasRequest.h>
#include <microstrain_mips/SetAccelBiasResponse.h>


namespace microstrain_mips
{

struct SetAccelBias
{

typedef SetAccelBiasRequest Request;
typedef SetAccelBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAccelBias
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetAccelBias > {
  static const char* value()
  {
    return "7f2cf85b824b45f9f629310ab233f3c6";
  }

  static const char* value(const ::microstrain_mips::SetAccelBias&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetAccelBias > {
  static const char* value()
  {
    return "microstrain_mips/SetAccelBias";
  }

  static const char* value(const ::microstrain_mips::SetAccelBias&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetAccelBiasRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetAccelBias >
template<>
struct MD5Sum< ::microstrain_mips::SetAccelBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetAccelBias >::value();
  }
  static const char* value(const ::microstrain_mips::SetAccelBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetAccelBiasRequest> should match
// service_traits::DataType< ::microstrain_mips::SetAccelBias >
template<>
struct DataType< ::microstrain_mips::SetAccelBiasRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetAccelBias >::value();
  }
  static const char* value(const ::microstrain_mips::SetAccelBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetAccelBiasResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetAccelBias >
template<>
struct MD5Sum< ::microstrain_mips::SetAccelBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetAccelBias >::value();
  }
  static const char* value(const ::microstrain_mips::SetAccelBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetAccelBiasResponse> should match
// service_traits::DataType< ::microstrain_mips::SetAccelBias >
template<>
struct DataType< ::microstrain_mips::SetAccelBiasResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetAccelBias >::value();
  }
  static const char* value(const ::microstrain_mips::SetAccelBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETACCELBIAS_H
