// Generated by gencpp from file microstrain_mips/SetDynamicsMode.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETDYNAMICSMODE_H
#define MICROSTRAIN_MIPS_MESSAGE_SETDYNAMICSMODE_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetDynamicsModeRequest.h>
#include <microstrain_mips/SetDynamicsModeResponse.h>


namespace microstrain_mips
{

struct SetDynamicsMode
{

typedef SetDynamicsModeRequest Request;
typedef SetDynamicsModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDynamicsMode
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetDynamicsMode > {
  static const char* value()
  {
    return "44114e5483e212902c0a057defaa1a3b";
  }

  static const char* value(const ::microstrain_mips::SetDynamicsMode&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetDynamicsMode > {
  static const char* value()
  {
    return "microstrain_mips/SetDynamicsMode";
  }

  static const char* value(const ::microstrain_mips::SetDynamicsMode&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetDynamicsModeRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetDynamicsMode >
template<>
struct MD5Sum< ::microstrain_mips::SetDynamicsModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetDynamicsMode >::value();
  }
  static const char* value(const ::microstrain_mips::SetDynamicsModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetDynamicsModeRequest> should match
// service_traits::DataType< ::microstrain_mips::SetDynamicsMode >
template<>
struct DataType< ::microstrain_mips::SetDynamicsModeRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetDynamicsMode >::value();
  }
  static const char* value(const ::microstrain_mips::SetDynamicsModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetDynamicsModeResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetDynamicsMode >
template<>
struct MD5Sum< ::microstrain_mips::SetDynamicsModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetDynamicsMode >::value();
  }
  static const char* value(const ::microstrain_mips::SetDynamicsModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetDynamicsModeResponse> should match
// service_traits::DataType< ::microstrain_mips::SetDynamicsMode >
template<>
struct DataType< ::microstrain_mips::SetDynamicsModeResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetDynamicsMode >::value();
  }
  static const char* value(const ::microstrain_mips::SetDynamicsModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETDYNAMICSMODE_H
