// Generated by gencpp from file microstrain_mips/SetEstimationControlFlags.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETESTIMATIONCONTROLFLAGS_H
#define MICROSTRAIN_MIPS_MESSAGE_SETESTIMATIONCONTROLFLAGS_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetEstimationControlFlagsRequest.h>
#include <microstrain_mips/SetEstimationControlFlagsResponse.h>


namespace microstrain_mips
{

struct SetEstimationControlFlags
{

typedef SetEstimationControlFlagsRequest Request;
typedef SetEstimationControlFlagsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEstimationControlFlags
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetEstimationControlFlags > {
  static const char* value()
  {
    return "692fa639072887f90a3c63c3c00dc9f6";
  }

  static const char* value(const ::microstrain_mips::SetEstimationControlFlags&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetEstimationControlFlags > {
  static const char* value()
  {
    return "microstrain_mips/SetEstimationControlFlags";
  }

  static const char* value(const ::microstrain_mips::SetEstimationControlFlags&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetEstimationControlFlagsRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetEstimationControlFlags >
template<>
struct MD5Sum< ::microstrain_mips::SetEstimationControlFlagsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetEstimationControlFlags >::value();
  }
  static const char* value(const ::microstrain_mips::SetEstimationControlFlagsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetEstimationControlFlagsRequest> should match
// service_traits::DataType< ::microstrain_mips::SetEstimationControlFlags >
template<>
struct DataType< ::microstrain_mips::SetEstimationControlFlagsRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetEstimationControlFlags >::value();
  }
  static const char* value(const ::microstrain_mips::SetEstimationControlFlagsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetEstimationControlFlagsResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetEstimationControlFlags >
template<>
struct MD5Sum< ::microstrain_mips::SetEstimationControlFlagsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetEstimationControlFlags >::value();
  }
  static const char* value(const ::microstrain_mips::SetEstimationControlFlagsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetEstimationControlFlagsResponse> should match
// service_traits::DataType< ::microstrain_mips::SetEstimationControlFlags >
template<>
struct DataType< ::microstrain_mips::SetEstimationControlFlagsResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetEstimationControlFlags >::value();
  }
  static const char* value(const ::microstrain_mips::SetEstimationControlFlagsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETESTIMATIONCONTROLFLAGS_H
