// Generated by gencpp from file microstrain_mips/SetFilterEuler.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETFILTEREULER_H
#define MICROSTRAIN_MIPS_MESSAGE_SETFILTEREULER_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetFilterEulerRequest.h>
#include <microstrain_mips/SetFilterEulerResponse.h>


namespace microstrain_mips
{

struct SetFilterEuler
{

typedef SetFilterEulerRequest Request;
typedef SetFilterEulerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFilterEuler
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetFilterEuler > {
  static const char* value()
  {
    return "dae0af6e9e855f125599090c94e6955e";
  }

  static const char* value(const ::microstrain_mips::SetFilterEuler&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetFilterEuler > {
  static const char* value()
  {
    return "microstrain_mips/SetFilterEuler";
  }

  static const char* value(const ::microstrain_mips::SetFilterEuler&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetFilterEulerRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetFilterEuler >
template<>
struct MD5Sum< ::microstrain_mips::SetFilterEulerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetFilterEuler >::value();
  }
  static const char* value(const ::microstrain_mips::SetFilterEulerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetFilterEulerRequest> should match
// service_traits::DataType< ::microstrain_mips::SetFilterEuler >
template<>
struct DataType< ::microstrain_mips::SetFilterEulerRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetFilterEuler >::value();
  }
  static const char* value(const ::microstrain_mips::SetFilterEulerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetFilterEulerResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetFilterEuler >
template<>
struct MD5Sum< ::microstrain_mips::SetFilterEulerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetFilterEuler >::value();
  }
  static const char* value(const ::microstrain_mips::SetFilterEulerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetFilterEulerResponse> should match
// service_traits::DataType< ::microstrain_mips::SetFilterEuler >
template<>
struct DataType< ::microstrain_mips::SetFilterEulerResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetFilterEuler >::value();
  }
  static const char* value(const ::microstrain_mips::SetFilterEulerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETFILTEREULER_H
