// Generated by gencpp from file microstrain_mips/SetFilterHeading.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETFILTERHEADING_H
#define MICROSTRAIN_MIPS_MESSAGE_SETFILTERHEADING_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetFilterHeadingRequest.h>
#include <microstrain_mips/SetFilterHeadingResponse.h>


namespace microstrain_mips
{

struct SetFilterHeading
{

typedef SetFilterHeadingRequest Request;
typedef SetFilterHeadingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFilterHeading
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetFilterHeading > {
  static const char* value()
  {
    return "194939c001a63802dc4131cae92cda22";
  }

  static const char* value(const ::microstrain_mips::SetFilterHeading&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetFilterHeading > {
  static const char* value()
  {
    return "microstrain_mips/SetFilterHeading";
  }

  static const char* value(const ::microstrain_mips::SetFilterHeading&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetFilterHeadingRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetFilterHeading >
template<>
struct MD5Sum< ::microstrain_mips::SetFilterHeadingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetFilterHeading >::value();
  }
  static const char* value(const ::microstrain_mips::SetFilterHeadingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetFilterHeadingRequest> should match
// service_traits::DataType< ::microstrain_mips::SetFilterHeading >
template<>
struct DataType< ::microstrain_mips::SetFilterHeadingRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetFilterHeading >::value();
  }
  static const char* value(const ::microstrain_mips::SetFilterHeadingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetFilterHeadingResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetFilterHeading >
template<>
struct MD5Sum< ::microstrain_mips::SetFilterHeadingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetFilterHeading >::value();
  }
  static const char* value(const ::microstrain_mips::SetFilterHeadingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetFilterHeadingResponse> should match
// service_traits::DataType< ::microstrain_mips::SetFilterHeading >
template<>
struct DataType< ::microstrain_mips::SetFilterHeadingResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetFilterHeading >::value();
  }
  static const char* value(const ::microstrain_mips::SetFilterHeadingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETFILTERHEADING_H
