// Generated by gencpp from file microstrain_mips/SetGyroBiasModel.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETGYROBIASMODEL_H
#define MICROSTRAIN_MIPS_MESSAGE_SETGYROBIASMODEL_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetGyroBiasModelRequest.h>
#include <microstrain_mips/SetGyroBiasModelResponse.h>


namespace microstrain_mips
{

struct SetGyroBiasModel
{

typedef SetGyroBiasModelRequest Request;
typedef SetGyroBiasModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGyroBiasModel
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetGyroBiasModel > {
  static const char* value()
  {
    return "f3cdd18c97add875be98974ab1d992b9";
  }

  static const char* value(const ::microstrain_mips::SetGyroBiasModel&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetGyroBiasModel > {
  static const char* value()
  {
    return "microstrain_mips/SetGyroBiasModel";
  }

  static const char* value(const ::microstrain_mips::SetGyroBiasModel&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetGyroBiasModelRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetGyroBiasModel >
template<>
struct MD5Sum< ::microstrain_mips::SetGyroBiasModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetGyroBiasModel >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetGyroBiasModelRequest> should match
// service_traits::DataType< ::microstrain_mips::SetGyroBiasModel >
template<>
struct DataType< ::microstrain_mips::SetGyroBiasModelRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetGyroBiasModel >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetGyroBiasModelResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetGyroBiasModel >
template<>
struct MD5Sum< ::microstrain_mips::SetGyroBiasModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetGyroBiasModel >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroBiasModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetGyroBiasModelResponse> should match
// service_traits::DataType< ::microstrain_mips::SetGyroBiasModel >
template<>
struct DataType< ::microstrain_mips::SetGyroBiasModelResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetGyroBiasModel >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroBiasModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETGYROBIASMODEL_H
