// Generated by gencpp from file microstrain_mips/SetGyroNoise.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETGYRONOISE_H
#define MICROSTRAIN_MIPS_MESSAGE_SETGYRONOISE_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetGyroNoiseRequest.h>
#include <microstrain_mips/SetGyroNoiseResponse.h>


namespace microstrain_mips
{

struct SetGyroNoise
{

typedef SetGyroNoiseRequest Request;
typedef SetGyroNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGyroNoise
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetGyroNoise > {
  static const char* value()
  {
    return "6a73c0e939ba0cee17d40a2e3a5f667f";
  }

  static const char* value(const ::microstrain_mips::SetGyroNoise&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetGyroNoise > {
  static const char* value()
  {
    return "microstrain_mips/SetGyroNoise";
  }

  static const char* value(const ::microstrain_mips::SetGyroNoise&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetGyroNoiseRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetGyroNoise >
template<>
struct MD5Sum< ::microstrain_mips::SetGyroNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetGyroNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetGyroNoiseRequest> should match
// service_traits::DataType< ::microstrain_mips::SetGyroNoise >
template<>
struct DataType< ::microstrain_mips::SetGyroNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetGyroNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetGyroNoiseResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetGyroNoise >
template<>
struct MD5Sum< ::microstrain_mips::SetGyroNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetGyroNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetGyroNoiseResponse> should match
// service_traits::DataType< ::microstrain_mips::SetGyroNoise >
template<>
struct DataType< ::microstrain_mips::SetGyroNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetGyroNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETGYRONOISE_H
