// Generated by gencpp from file microstrain_mips/SetGyroBias.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETGYROBIAS_H
#define MICROSTRAIN_MIPS_MESSAGE_SETGYROBIAS_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetGyroBiasRequest.h>
#include <microstrain_mips/SetGyroBiasResponse.h>


namespace microstrain_mips
{

struct SetGyroBias
{

typedef SetGyroBiasRequest Request;
typedef SetGyroBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGyroBias
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetGyroBias > {
  static const char* value()
  {
    return "7f2cf85b824b45f9f629310ab233f3c6";
  }

  static const char* value(const ::microstrain_mips::SetGyroBias&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetGyroBias > {
  static const char* value()
  {
    return "microstrain_mips/SetGyroBias";
  }

  static const char* value(const ::microstrain_mips::SetGyroBias&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetGyroBiasRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetGyroBias >
template<>
struct MD5Sum< ::microstrain_mips::SetGyroBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetGyroBias >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetGyroBiasRequest> should match
// service_traits::DataType< ::microstrain_mips::SetGyroBias >
template<>
struct DataType< ::microstrain_mips::SetGyroBiasRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetGyroBias >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetGyroBiasResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetGyroBias >
template<>
struct MD5Sum< ::microstrain_mips::SetGyroBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetGyroBias >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetGyroBiasResponse> should match
// service_traits::DataType< ::microstrain_mips::SetGyroBias >
template<>
struct DataType< ::microstrain_mips::SetGyroBiasResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetGyroBias >::value();
  }
  static const char* value(const ::microstrain_mips::SetGyroBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETGYROBIAS_H
