// Generated by gencpp from file microstrain_mips/SetHardIronValues.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETHARDIRONVALUES_H
#define MICROSTRAIN_MIPS_MESSAGE_SETHARDIRONVALUES_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetHardIronValuesRequest.h>
#include <microstrain_mips/SetHardIronValuesResponse.h>


namespace microstrain_mips
{

struct SetHardIronValues
{

typedef SetHardIronValuesRequest Request;
typedef SetHardIronValuesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHardIronValues
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetHardIronValues > {
  static const char* value()
  {
    return "7f2cf85b824b45f9f629310ab233f3c6";
  }

  static const char* value(const ::microstrain_mips::SetHardIronValues&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetHardIronValues > {
  static const char* value()
  {
    return "microstrain_mips/SetHardIronValues";
  }

  static const char* value(const ::microstrain_mips::SetHardIronValues&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetHardIronValuesRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetHardIronValues >
template<>
struct MD5Sum< ::microstrain_mips::SetHardIronValuesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetHardIronValues >::value();
  }
  static const char* value(const ::microstrain_mips::SetHardIronValuesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetHardIronValuesRequest> should match
// service_traits::DataType< ::microstrain_mips::SetHardIronValues >
template<>
struct DataType< ::microstrain_mips::SetHardIronValuesRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetHardIronValues >::value();
  }
  static const char* value(const ::microstrain_mips::SetHardIronValuesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetHardIronValuesResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetHardIronValues >
template<>
struct MD5Sum< ::microstrain_mips::SetHardIronValuesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetHardIronValues >::value();
  }
  static const char* value(const ::microstrain_mips::SetHardIronValuesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetHardIronValuesResponse> should match
// service_traits::DataType< ::microstrain_mips::SetHardIronValues >
template<>
struct DataType< ::microstrain_mips::SetHardIronValuesResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetHardIronValues >::value();
  }
  static const char* value(const ::microstrain_mips::SetHardIronValuesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETHARDIRONVALUES_H
