// Generated by gencpp from file microstrain_mips/SetMagNoise.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETMAGNOISE_H
#define MICROSTRAIN_MIPS_MESSAGE_SETMAGNOISE_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetMagNoiseRequest.h>
#include <microstrain_mips/SetMagNoiseResponse.h>


namespace microstrain_mips
{

struct SetMagNoise
{

typedef SetMagNoiseRequest Request;
typedef SetMagNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMagNoise
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetMagNoise > {
  static const char* value()
  {
    return "6a73c0e939ba0cee17d40a2e3a5f667f";
  }

  static const char* value(const ::microstrain_mips::SetMagNoise&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetMagNoise > {
  static const char* value()
  {
    return "microstrain_mips/SetMagNoise";
  }

  static const char* value(const ::microstrain_mips::SetMagNoise&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetMagNoiseRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetMagNoise >
template<>
struct MD5Sum< ::microstrain_mips::SetMagNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetMagNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetMagNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetMagNoiseRequest> should match
// service_traits::DataType< ::microstrain_mips::SetMagNoise >
template<>
struct DataType< ::microstrain_mips::SetMagNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetMagNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetMagNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetMagNoiseResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetMagNoise >
template<>
struct MD5Sum< ::microstrain_mips::SetMagNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetMagNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetMagNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetMagNoiseResponse> should match
// service_traits::DataType< ::microstrain_mips::SetMagNoise >
template<>
struct DataType< ::microstrain_mips::SetMagNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetMagNoise >::value();
  }
  static const char* value(const ::microstrain_mips::SetMagNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETMAGNOISE_H
