// Generated by gencpp from file microstrain_mips/SetMagDipAdaptiveVals.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETMAGDIPADAPTIVEVALS_H
#define MICROSTRAIN_MIPS_MESSAGE_SETMAGDIPADAPTIVEVALS_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetMagDipAdaptiveValsRequest.h>
#include <microstrain_mips/SetMagDipAdaptiveValsResponse.h>


namespace microstrain_mips
{

struct SetMagDipAdaptiveVals
{

typedef SetMagDipAdaptiveValsRequest Request;
typedef SetMagDipAdaptiveValsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMagDipAdaptiveVals
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetMagDipAdaptiveVals > {
  static const char* value()
  {
    return "c71450f947e543c107e6e7b633ac2f16";
  }

  static const char* value(const ::microstrain_mips::SetMagDipAdaptiveVals&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetMagDipAdaptiveVals > {
  static const char* value()
  {
    return "microstrain_mips/SetMagDipAdaptiveVals";
  }

  static const char* value(const ::microstrain_mips::SetMagDipAdaptiveVals&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetMagDipAdaptiveValsRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetMagDipAdaptiveVals >
template<>
struct MD5Sum< ::microstrain_mips::SetMagDipAdaptiveValsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::microstrain_mips::SetMagDipAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetMagDipAdaptiveValsRequest> should match
// service_traits::DataType< ::microstrain_mips::SetMagDipAdaptiveVals >
template<>
struct DataType< ::microstrain_mips::SetMagDipAdaptiveValsRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::microstrain_mips::SetMagDipAdaptiveValsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetMagDipAdaptiveValsResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetMagDipAdaptiveVals >
template<>
struct MD5Sum< ::microstrain_mips::SetMagDipAdaptiveValsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::microstrain_mips::SetMagDipAdaptiveValsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetMagDipAdaptiveValsResponse> should match
// service_traits::DataType< ::microstrain_mips::SetMagDipAdaptiveVals >
template<>
struct DataType< ::microstrain_mips::SetMagDipAdaptiveValsResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetMagDipAdaptiveVals >::value();
  }
  static const char* value(const ::microstrain_mips::SetMagDipAdaptiveValsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETMAGDIPADAPTIVEVALS_H
