// Generated by gencpp from file microstrain_mips/SetReferencePosition.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETREFERENCEPOSITION_H
#define MICROSTRAIN_MIPS_MESSAGE_SETREFERENCEPOSITION_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetReferencePositionRequest.h>
#include <microstrain_mips/SetReferencePositionResponse.h>


namespace microstrain_mips
{

struct SetReferencePosition
{

typedef SetReferencePositionRequest Request;
typedef SetReferencePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetReferencePosition
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetReferencePosition > {
  static const char* value()
  {
    return "eed8c009a979878261617f53e8264ddc";
  }

  static const char* value(const ::microstrain_mips::SetReferencePosition&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetReferencePosition > {
  static const char* value()
  {
    return "microstrain_mips/SetReferencePosition";
  }

  static const char* value(const ::microstrain_mips::SetReferencePosition&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetReferencePositionRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetReferencePosition >
template<>
struct MD5Sum< ::microstrain_mips::SetReferencePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetReferencePosition >::value();
  }
  static const char* value(const ::microstrain_mips::SetReferencePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetReferencePositionRequest> should match
// service_traits::DataType< ::microstrain_mips::SetReferencePosition >
template<>
struct DataType< ::microstrain_mips::SetReferencePositionRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetReferencePosition >::value();
  }
  static const char* value(const ::microstrain_mips::SetReferencePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetReferencePositionResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetReferencePosition >
template<>
struct MD5Sum< ::microstrain_mips::SetReferencePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetReferencePosition >::value();
  }
  static const char* value(const ::microstrain_mips::SetReferencePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetReferencePositionResponse> should match
// service_traits::DataType< ::microstrain_mips::SetReferencePosition >
template<>
struct DataType< ::microstrain_mips::SetReferencePositionResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetReferencePosition >::value();
  }
  static const char* value(const ::microstrain_mips::SetReferencePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETREFERENCEPOSITION_H
