// Generated by gencpp from file microstrain_mips/SetSensorVehicleFrameOffset.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETSENSORVEHICLEFRAMEOFFSET_H
#define MICROSTRAIN_MIPS_MESSAGE_SETSENSORVEHICLEFRAMEOFFSET_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetSensorVehicleFrameOffsetRequest.h>
#include <microstrain_mips/SetSensorVehicleFrameOffsetResponse.h>


namespace microstrain_mips
{

struct SetSensorVehicleFrameOffset
{

typedef SetSensorVehicleFrameOffsetRequest Request;
typedef SetSensorVehicleFrameOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensorVehicleFrameOffset
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffset > {
  static const char* value()
  {
    return "17d27ff1259ce523baf9de57b7c37e18";
  }

  static const char* value(const ::microstrain_mips::SetSensorVehicleFrameOffset&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetSensorVehicleFrameOffset > {
  static const char* value()
  {
    return "microstrain_mips/SetSensorVehicleFrameOffset";
  }

  static const char* value(const ::microstrain_mips::SetSensorVehicleFrameOffset&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffsetRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffset >
template<>
struct MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffset >::value();
  }
  static const char* value(const ::microstrain_mips::SetSensorVehicleFrameOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetSensorVehicleFrameOffsetRequest> should match
// service_traits::DataType< ::microstrain_mips::SetSensorVehicleFrameOffset >
template<>
struct DataType< ::microstrain_mips::SetSensorVehicleFrameOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetSensorVehicleFrameOffset >::value();
  }
  static const char* value(const ::microstrain_mips::SetSensorVehicleFrameOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffsetResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffset >
template<>
struct MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetSensorVehicleFrameOffset >::value();
  }
  static const char* value(const ::microstrain_mips::SetSensorVehicleFrameOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetSensorVehicleFrameOffsetResponse> should match
// service_traits::DataType< ::microstrain_mips::SetSensorVehicleFrameOffset >
template<>
struct DataType< ::microstrain_mips::SetSensorVehicleFrameOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetSensorVehicleFrameOffset >::value();
  }
  static const char* value(const ::microstrain_mips::SetSensorVehicleFrameOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETSENSORVEHICLEFRAMEOFFSET_H
