// Generated by gencpp from file microstrain_mips/SetTareOrientation.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETTAREORIENTATION_H
#define MICROSTRAIN_MIPS_MESSAGE_SETTAREORIENTATION_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetTareOrientationRequest.h>
#include <microstrain_mips/SetTareOrientationResponse.h>


namespace microstrain_mips
{

struct SetTareOrientation
{

typedef SetTareOrientationRequest Request;
typedef SetTareOrientationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTareOrientation
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetTareOrientation > {
  static const char* value()
  {
    return "75811cb68205ae4484ed796af90a6397";
  }

  static const char* value(const ::microstrain_mips::SetTareOrientation&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetTareOrientation > {
  static const char* value()
  {
    return "microstrain_mips/SetTareOrientation";
  }

  static const char* value(const ::microstrain_mips::SetTareOrientation&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetTareOrientationRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetTareOrientation >
template<>
struct MD5Sum< ::microstrain_mips::SetTareOrientationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetTareOrientation >::value();
  }
  static const char* value(const ::microstrain_mips::SetTareOrientationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetTareOrientationRequest> should match
// service_traits::DataType< ::microstrain_mips::SetTareOrientation >
template<>
struct DataType< ::microstrain_mips::SetTareOrientationRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetTareOrientation >::value();
  }
  static const char* value(const ::microstrain_mips::SetTareOrientationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetTareOrientationResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetTareOrientation >
template<>
struct MD5Sum< ::microstrain_mips::SetTareOrientationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetTareOrientation >::value();
  }
  static const char* value(const ::microstrain_mips::SetTareOrientationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetTareOrientationResponse> should match
// service_traits::DataType< ::microstrain_mips::SetTareOrientation >
template<>
struct DataType< ::microstrain_mips::SetTareOrientationResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetTareOrientation >::value();
  }
  static const char* value(const ::microstrain_mips::SetTareOrientationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETTAREORIENTATION_H
