// Generated by gencpp from file microstrain_mips/SetZeroAngleUpdateThreshold.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETZEROANGLEUPDATETHRESHOLD_H
#define MICROSTRAIN_MIPS_MESSAGE_SETZEROANGLEUPDATETHRESHOLD_H

#include <ros/service_traits.h>


#include <microstrain_mips/SetZeroAngleUpdateThresholdRequest.h>
#include <microstrain_mips/SetZeroAngleUpdateThresholdResponse.h>


namespace microstrain_mips
{

struct SetZeroAngleUpdateThreshold
{

typedef SetZeroAngleUpdateThresholdRequest Request;
typedef SetZeroAngleUpdateThresholdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetZeroAngleUpdateThreshold
} // namespace microstrain_mips


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThreshold > {
  static const char* value()
  {
    return "ea1115ed39d8a581530c7c251ee443e6";
  }

  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThreshold&) { return value(); }
};

template<>
struct DataType< ::microstrain_mips::SetZeroAngleUpdateThreshold > {
  static const char* value()
  {
    return "microstrain_mips/SetZeroAngleUpdateThreshold";
  }

  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThreshold&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest> should match
// service_traits::MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThreshold >
template<>
struct MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest> should match
// service_traits::DataType< ::microstrain_mips::SetZeroAngleUpdateThreshold >
template<>
struct DataType< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThresholdResponse> should match
// service_traits::MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThreshold >
template<>
struct MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThresholdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThresholdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_mips::SetZeroAngleUpdateThresholdResponse> should match
// service_traits::DataType< ::microstrain_mips::SetZeroAngleUpdateThreshold >
template<>
struct DataType< ::microstrain_mips::SetZeroAngleUpdateThresholdResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_mips::SetZeroAngleUpdateThreshold >::value();
  }
  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThresholdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETZEROANGLEUPDATETHRESHOLD_H
