// Generated by gencpp from file microstrain_mips/SetZeroAngleUpdateThresholdRequest.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_MIPS_MESSAGE_SETZEROANGLEUPDATETHRESHOLDREQUEST_H
#define MICROSTRAIN_MIPS_MESSAGE_SETZEROANGLEUPDATETHRESHOLDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_mips
{
template <class ContainerAllocator>
struct SetZeroAngleUpdateThresholdRequest_
{
  typedef SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> Type;

  SetZeroAngleUpdateThresholdRequest_()
    : enable(0)
    , threshold(0.0)  {
    }
  SetZeroAngleUpdateThresholdRequest_(const ContainerAllocator& _alloc)
    : enable(0)
    , threshold(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _enable_type;
  _enable_type enable;

   typedef float _threshold_type;
  _threshold_type threshold;





  typedef boost::shared_ptr< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetZeroAngleUpdateThresholdRequest_

typedef ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<std::allocator<void> > SetZeroAngleUpdateThresholdRequest;

typedef boost::shared_ptr< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest > SetZeroAngleUpdateThresholdRequestPtr;
typedef boost::shared_ptr< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest const> SetZeroAngleUpdateThresholdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator1> & lhs, const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable &&
    lhs.threshold == rhs.threshold;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator1> & lhs, const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_mips

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6eacdc5ab3df5e6c977f6645124a7f61";
  }

  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6eacdc5ab3df5e6cULL;
  static const uint64_t static_value2 = 0x977f6645124a7f61ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_mips/SetZeroAngleUpdateThresholdRequest";
  }

  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 enable\n"
"float32 threshold\n"
;
  }

  static const char* value(const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
      stream.next(m.threshold);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetZeroAngleUpdateThresholdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_mips::SetZeroAngleUpdateThresholdRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<int8_t>::stream(s, indent + "  ", v.enable);
    s << indent << "threshold: ";
    Printer<float>::stream(s, indent + "  ", v.threshold);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_MIPS_MESSAGE_SETZEROANGLEUPDATETHRESHOLDREQUEST_H
