// Generated by gencpp from file ssl_frontier_selection/CheckCollisionRequest.msg
// DO NOT EDIT!


#ifndef SSL_FRONTIER_SELECTION_MESSAGE_CHECKCOLLISIONREQUEST_H
#define SSL_FRONTIER_SELECTION_MESSAGE_CHECKCOLLISIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace ssl_frontier_selection
{
template <class ContainerAllocator>
struct CheckCollisionRequest_
{
  typedef CheckCollisionRequest_<ContainerAllocator> Type;

  CheckCollisionRequest_()
    : start()
    , end()  {
    }
  CheckCollisionRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , end(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _end_type;
  _end_type end;





  typedef boost::shared_ptr< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckCollisionRequest_

typedef ::ssl_frontier_selection::CheckCollisionRequest_<std::allocator<void> > CheckCollisionRequest;

typedef boost::shared_ptr< ::ssl_frontier_selection::CheckCollisionRequest > CheckCollisionRequestPtr;
typedef boost::shared_ptr< ::ssl_frontier_selection::CheckCollisionRequest const> CheckCollisionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator1> & lhs, const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.end == rhs.end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator1> & lhs, const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ssl_frontier_selection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c43d9dccc054ebcc44daea526db34ad2";
  }

  static const char* value(const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc43d9dccc054ebccULL;
  static const uint64_t static_value2 = 0x44daea526db34ad2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssl_frontier_selection/CheckCollisionRequest";
  }

  static const char* value(const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request\n"
"geometry_msgs/PoseStamped start\n"
"geometry_msgs/PoseStamped end\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckCollisionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssl_frontier_selection::CheckCollisionRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSL_FRONTIER_SELECTION_MESSAGE_CHECKCOLLISIONREQUEST_H
