// Generated by gencpp from file ssl_frontier_selection/PruneFrontiersResponse.msg
// DO NOT EDIT!


#ifndef SSL_FRONTIER_SELECTION_MESSAGE_PRUNEFRONTIERSRESPONSE_H
#define SSL_FRONTIER_SELECTION_MESSAGE_PRUNEFRONTIERSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ssl_frontier_selection
{
template <class ContainerAllocator>
struct PruneFrontiersResponse_
{
  typedef PruneFrontiersResponse_<ContainerAllocator> Type;

  PruneFrontiersResponse_()
    : pruned()  {
    }
  PruneFrontiersResponse_(const ContainerAllocator& _alloc)
    : pruned(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _pruned_type;
  _pruned_type pruned;





  typedef boost::shared_ptr< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PruneFrontiersResponse_

typedef ::ssl_frontier_selection::PruneFrontiersResponse_<std::allocator<void> > PruneFrontiersResponse;

typedef boost::shared_ptr< ::ssl_frontier_selection::PruneFrontiersResponse > PruneFrontiersResponsePtr;
typedef boost::shared_ptr< ::ssl_frontier_selection::PruneFrontiersResponse const> PruneFrontiersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator1> & lhs, const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pruned == rhs.pruned;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator1> & lhs, const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ssl_frontier_selection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e0b05d933c831596f58cdbe4fb9041b";
  }

  static const char* value(const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e0b05d933c83159ULL;
  static const uint64_t static_value2 = 0x6f58cdbe4fb9041bULL;
};

template<class ContainerAllocator>
struct DataType< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssl_frontier_selection/PruneFrontiersResponse";
  }

  static const char* value(const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response\n"
"int32[] pruned \n"
;
  }

  static const char* value(const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pruned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PruneFrontiersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssl_frontier_selection::PruneFrontiersResponse_<ContainerAllocator>& v)
  {
    s << indent << "pruned[]" << std::endl;
    for (size_t i = 0; i < v.pruned.size(); ++i)
    {
      s << indent << "  pruned[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pruned[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSL_FRONTIER_SELECTION_MESSAGE_PRUNEFRONTIERSRESPONSE_H
