// Generated by gencpp from file ssl_frontier_selection/RemoveFrontierResponse.msg
// DO NOT EDIT!


#ifndef SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIERRESPONSE_H
#define SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ssl_frontier_selection
{
template <class ContainerAllocator>
struct RemoveFrontierResponse_
{
  typedef RemoveFrontierResponse_<ContainerAllocator> Type;

  RemoveFrontierResponse_()
    : success(false)  {
    }
  RemoveFrontierResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveFrontierResponse_

typedef ::ssl_frontier_selection::RemoveFrontierResponse_<std::allocator<void> > RemoveFrontierResponse;

typedef boost::shared_ptr< ::ssl_frontier_selection::RemoveFrontierResponse > RemoveFrontierResponsePtr;
typedef boost::shared_ptr< ::ssl_frontier_selection::RemoveFrontierResponse const> RemoveFrontierResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator1> & lhs, const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator1> & lhs, const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ssl_frontier_selection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssl_frontier_selection/RemoveFrontierResponse";
  }

  static const char* value(const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response\n"
"bool success\n"
;
  }

  static const char* value(const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveFrontierResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssl_frontier_selection::RemoveFrontierResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIERRESPONSE_H
