// Generated by gencpp from file ssl_frontier_selection/RemoveFrontier.msg
// DO NOT EDIT!


#ifndef SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIER_H
#define SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIER_H

#include <ros/service_traits.h>


#include <ssl_frontier_selection/RemoveFrontierRequest.h>
#include <ssl_frontier_selection/RemoveFrontierResponse.h>


namespace ssl_frontier_selection
{

struct RemoveFrontier
{

typedef RemoveFrontierRequest Request;
typedef RemoveFrontierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveFrontier
} // namespace ssl_frontier_selection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ssl_frontier_selection::RemoveFrontier > {
  static const char* value()
  {
    return "f66e2f1a2389241ede90395037adaed8";
  }

  static const char* value(const ::ssl_frontier_selection::RemoveFrontier&) { return value(); }
};

template<>
struct DataType< ::ssl_frontier_selection::RemoveFrontier > {
  static const char* value()
  {
    return "ssl_frontier_selection/RemoveFrontier";
  }

  static const char* value(const ::ssl_frontier_selection::RemoveFrontier&) { return value(); }
};


// service_traits::MD5Sum< ::ssl_frontier_selection::RemoveFrontierRequest> should match
// service_traits::MD5Sum< ::ssl_frontier_selection::RemoveFrontier >
template<>
struct MD5Sum< ::ssl_frontier_selection::RemoveFrontierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ssl_frontier_selection::RemoveFrontier >::value();
  }
  static const char* value(const ::ssl_frontier_selection::RemoveFrontierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ssl_frontier_selection::RemoveFrontierRequest> should match
// service_traits::DataType< ::ssl_frontier_selection::RemoveFrontier >
template<>
struct DataType< ::ssl_frontier_selection::RemoveFrontierRequest>
{
  static const char* value()
  {
    return DataType< ::ssl_frontier_selection::RemoveFrontier >::value();
  }
  static const char* value(const ::ssl_frontier_selection::RemoveFrontierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ssl_frontier_selection::RemoveFrontierResponse> should match
// service_traits::MD5Sum< ::ssl_frontier_selection::RemoveFrontier >
template<>
struct MD5Sum< ::ssl_frontier_selection::RemoveFrontierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ssl_frontier_selection::RemoveFrontier >::value();
  }
  static const char* value(const ::ssl_frontier_selection::RemoveFrontierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ssl_frontier_selection::RemoveFrontierResponse> should match
// service_traits::DataType< ::ssl_frontier_selection::RemoveFrontier >
template<>
struct DataType< ::ssl_frontier_selection::RemoveFrontierResponse>
{
  static const char* value()
  {
    return DataType< ::ssl_frontier_selection::RemoveFrontier >::value();
  }
  static const char* value(const ::ssl_frontier_selection::RemoveFrontierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIER_H
