// Generated by gencpp from file ssl_frontier_selection/RemoveFrontierRequest.msg
// DO NOT EDIT!


#ifndef SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIERREQUEST_H
#define SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ssl_frontier_selection
{
template <class ContainerAllocator>
struct RemoveFrontierRequest_
{
  typedef RemoveFrontierRequest_<ContainerAllocator> Type;

  RemoveFrontierRequest_()
    : id(0)  {
    }
  RemoveFrontierRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveFrontierRequest_

typedef ::ssl_frontier_selection::RemoveFrontierRequest_<std::allocator<void> > RemoveFrontierRequest;

typedef boost::shared_ptr< ::ssl_frontier_selection::RemoveFrontierRequest > RemoveFrontierRequestPtr;
typedef boost::shared_ptr< ::ssl_frontier_selection::RemoveFrontierRequest const> RemoveFrontierRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator1> & lhs, const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator1> & lhs, const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ssl_frontier_selection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssl_frontier_selection/RemoveFrontierRequest";
  }

  static const char* value(const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request\n"
"int32 id\n"
;
  }

  static const char* value(const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveFrontierRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssl_frontier_selection::RemoveFrontierRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSL_FRONTIER_SELECTION_MESSAGE_REMOVEFRONTIERREQUEST_H
