// Generated by gencpp from file ssl_frontier_selection/StampMapRequest.msg
// DO NOT EDIT!


#ifndef SSL_FRONTIER_SELECTION_MESSAGE_STAMPMAPREQUEST_H
#define SSL_FRONTIER_SELECTION_MESSAGE_STAMPMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ssl_frontier_selection
{
template <class ContainerAllocator>
struct StampMapRequest_
{
  typedef StampMapRequest_<ContainerAllocator> Type;

  StampMapRequest_()
    {
    }
  StampMapRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StampMapRequest_

typedef ::ssl_frontier_selection::StampMapRequest_<std::allocator<void> > StampMapRequest;

typedef boost::shared_ptr< ::ssl_frontier_selection::StampMapRequest > StampMapRequestPtr;
typedef boost::shared_ptr< ::ssl_frontier_selection::StampMapRequest const> StampMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ssl_frontier_selection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssl_frontier_selection/StampMapRequest";
  }

  static const char* value(const ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request\n"
"\n"
;
  }

  static const char* value(const ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StampMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ssl_frontier_selection::StampMapRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SSL_FRONTIER_SELECTION_MESSAGE_STAMPMAPREQUEST_H
