# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from spot_msgs/MobilityParams.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class MobilityParams(genpy.Message):
  _md5sum = "87bda7c4fbd2a6b19bdc029effa9f715"
  _type = "spot_msgs/MobilityParams"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose body_control
uint32 locomotion_hint
bool stair_hint

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['body_control','locomotion_hint','stair_hint']
  _slot_types = ['geometry_msgs/Pose','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       body_control,locomotion_hint,stair_hint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MobilityParams, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.body_control is None:
        self.body_control = geometry_msgs.msg.Pose()
      if self.locomotion_hint is None:
        self.locomotion_hint = 0
      if self.stair_hint is None:
        self.stair_hint = False
    else:
      self.body_control = geometry_msgs.msg.Pose()
      self.locomotion_hint = 0
      self.stair_hint = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7dIB().pack(_x.body_control.position.x, _x.body_control.position.y, _x.body_control.position.z, _x.body_control.orientation.x, _x.body_control.orientation.y, _x.body_control.orientation.z, _x.body_control.orientation.w, _x.locomotion_hint, _x.stair_hint))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.body_control is None:
        self.body_control = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.body_control.position.x, _x.body_control.position.y, _x.body_control.position.z, _x.body_control.orientation.x, _x.body_control.orientation.y, _x.body_control.orientation.z, _x.body_control.orientation.w, _x.locomotion_hint, _x.stair_hint,) = _get_struct_7dIB().unpack(str[start:end])
      self.stair_hint = bool(self.stair_hint)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7dIB().pack(_x.body_control.position.x, _x.body_control.position.y, _x.body_control.position.z, _x.body_control.orientation.x, _x.body_control.orientation.y, _x.body_control.orientation.z, _x.body_control.orientation.w, _x.locomotion_hint, _x.stair_hint))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.body_control is None:
        self.body_control = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.body_control.position.x, _x.body_control.position.y, _x.body_control.position.z, _x.body_control.orientation.x, _x.body_control.orientation.y, _x.body_control.orientation.z, _x.body_control.orientation.w, _x.locomotion_hint, _x.stair_hint,) = _get_struct_7dIB().unpack(str[start:end])
      self.stair_hint = bool(self.stair_hint)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dIB = None
def _get_struct_7dIB():
    global _struct_7dIB
    if _struct_7dIB is None:
        _struct_7dIB = struct.Struct("<7dIB")
    return _struct_7dIB
