# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from spot_msgs/NavigateToGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NavigateToGoal(genpy.Message):
  _md5sum = "f9af434c1c55a1da6434e77de4087aaf"
  _type = "spot_msgs/NavigateToGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
string upload_path # Absolute path to map_directory, which is downloaded from tablet controller
string navigate_to # Waypoint id string for where to go
bool initial_localization_fiducial   # Tells the initializer whether to use fiducials
string initial_localization_waypoint # Waypoint id to trigger localization 
"""
  __slots__ = ['upload_path','navigate_to','initial_localization_fiducial','initial_localization_waypoint']
  _slot_types = ['string','string','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       upload_path,navigate_to,initial_localization_fiducial,initial_localization_waypoint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NavigateToGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.upload_path is None:
        self.upload_path = ''
      if self.navigate_to is None:
        self.navigate_to = ''
      if self.initial_localization_fiducial is None:
        self.initial_localization_fiducial = False
      if self.initial_localization_waypoint is None:
        self.initial_localization_waypoint = ''
    else:
      self.upload_path = ''
      self.navigate_to = ''
      self.initial_localization_fiducial = False
      self.initial_localization_waypoint = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.upload_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.navigate_to
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.initial_localization_fiducial
      buff.write(_get_struct_B().pack(_x))
      _x = self.initial_localization_waypoint
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.upload_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.upload_path = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.navigate_to = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.navigate_to = str[start:end]
      start = end
      end += 1
      (self.initial_localization_fiducial,) = _get_struct_B().unpack(str[start:end])
      self.initial_localization_fiducial = bool(self.initial_localization_fiducial)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.initial_localization_waypoint = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.initial_localization_waypoint = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.upload_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.navigate_to
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.initial_localization_fiducial
      buff.write(_get_struct_B().pack(_x))
      _x = self.initial_localization_waypoint
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.upload_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.upload_path = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.navigate_to = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.navigate_to = str[start:end]
      start = end
      end += 1
      (self.initial_localization_fiducial,) = _get_struct_B().unpack(str[start:end])
      self.initial_localization_fiducial = bool(self.initial_localization_fiducial)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.initial_localization_waypoint = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.initial_localization_waypoint = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
