(cl:defpackage spot_msgs-srv
  (:use )
  (:export
   "CLEARBEHAVIORFAULT"
   "<CLEARBEHAVIORFAULT-REQUEST>"
   "CLEARBEHAVIORFAULT-REQUEST"
   "<CLEARBEHAVIORFAULT-RESPONSE>"
   "CLEARBEHAVIORFAULT-RESPONSE"
   "LISTGRAPH"
   "<LISTGRAPH-REQUEST>"
   "LISTGRAPH-REQUEST"
   "<LISTGRAPH-RESPONSE>"
   "LISTGRAPH-RESPONSE"
   "SETLOCOMOTION"
   "<SETLOCOMOTION-REQUEST>"
   "SETLOCOMOTION-REQUEST"
   "<SETLOCOMOTION-RESPONSE>"
   "SETLOCOMOTION-RESPONSE"
   "SETVELOCITY"
   "<SETVELOCITY-REQUEST>"
   "SETVELOCITY-REQUEST"
   "<SETVELOCITY-RESPONSE>"
   "SETVELOCITY-RESPONSE"
  ))

