(cl:in-package spot_msgs-msg)
(cl:export '(UPLOAD_PATH-VAL
          UPLOAD_PATH
          NAVIGATE_TO-VAL
          NAVIGATE_TO
          INITIAL_LOCALIZATION_FIDUCIAL-VAL
          INITIAL_LOCALIZATION_FIDUCIAL
          INITIAL_LOCALIZATION_WAYPOINT-VAL
          INITIAL_LOCALIZATION_WAYPOINT
))