// Auto-generated. Do not edit!

// (in-package spot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class MaplessTrajectoryFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.error = null;
      this.feedback = null;
      this.current_attempt = null;
    }
    else {
      if (initObj.hasOwnProperty('error')) {
        this.error = initObj.error
      }
      else {
        this.error = new geometry_msgs.msg.Pose();
      }
      if (initObj.hasOwnProperty('feedback')) {
        this.feedback = initObj.feedback
      }
      else {
        this.feedback = '';
      }
      if (initObj.hasOwnProperty('current_attempt')) {
        this.current_attempt = initObj.current_attempt
      }
      else {
        this.current_attempt = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MaplessTrajectoryFeedback
    // Serialize message field [error]
    bufferOffset = geometry_msgs.msg.Pose.serialize(obj.error, buffer, bufferOffset);
    // Serialize message field [feedback]
    bufferOffset = _serializer.string(obj.feedback, buffer, bufferOffset);
    // Serialize message field [current_attempt]
    bufferOffset = _serializer.int32(obj.current_attempt, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MaplessTrajectoryFeedback
    let len;
    let data = new MaplessTrajectoryFeedback(null);
    // Deserialize message field [error]
    data.error = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset);
    // Deserialize message field [feedback]
    data.feedback = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [current_attempt]
    data.current_attempt = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.feedback);
    return length + 64;
  }

  static datatype() {
    // Returns string type for a message object
    return 'spot_msgs/MaplessTrajectoryFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '98751604b46a4e51af4fd37d5b14d6e7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    geometry_msgs/Pose error
    string feedback
    int32 current_attempt
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MaplessTrajectoryFeedback(null);
    if (msg.error !== undefined) {
      resolved.error = geometry_msgs.msg.Pose.Resolve(msg.error)
    }
    else {
      resolved.error = new geometry_msgs.msg.Pose()
    }

    if (msg.feedback !== undefined) {
      resolved.feedback = msg.feedback;
    }
    else {
      resolved.feedback = ''
    }

    if (msg.current_attempt !== undefined) {
      resolved.current_attempt = msg.current_attempt;
    }
    else {
      resolved.current_attempt = 0
    }

    return resolved;
    }
};

module.exports = MaplessTrajectoryFeedback;
