// Auto-generated. Do not edit!

// (in-package spot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class NavigateToGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.upload_path = null;
      this.navigate_to = null;
      this.initial_localization_fiducial = null;
      this.initial_localization_waypoint = null;
    }
    else {
      if (initObj.hasOwnProperty('upload_path')) {
        this.upload_path = initObj.upload_path
      }
      else {
        this.upload_path = '';
      }
      if (initObj.hasOwnProperty('navigate_to')) {
        this.navigate_to = initObj.navigate_to
      }
      else {
        this.navigate_to = '';
      }
      if (initObj.hasOwnProperty('initial_localization_fiducial')) {
        this.initial_localization_fiducial = initObj.initial_localization_fiducial
      }
      else {
        this.initial_localization_fiducial = false;
      }
      if (initObj.hasOwnProperty('initial_localization_waypoint')) {
        this.initial_localization_waypoint = initObj.initial_localization_waypoint
      }
      else {
        this.initial_localization_waypoint = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavigateToGoal
    // Serialize message field [upload_path]
    bufferOffset = _serializer.string(obj.upload_path, buffer, bufferOffset);
    // Serialize message field [navigate_to]
    bufferOffset = _serializer.string(obj.navigate_to, buffer, bufferOffset);
    // Serialize message field [initial_localization_fiducial]
    bufferOffset = _serializer.bool(obj.initial_localization_fiducial, buffer, bufferOffset);
    // Serialize message field [initial_localization_waypoint]
    bufferOffset = _serializer.string(obj.initial_localization_waypoint, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavigateToGoal
    let len;
    let data = new NavigateToGoal(null);
    // Deserialize message field [upload_path]
    data.upload_path = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [navigate_to]
    data.navigate_to = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [initial_localization_fiducial]
    data.initial_localization_fiducial = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [initial_localization_waypoint]
    data.initial_localization_waypoint = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.upload_path);
    length += _getByteLength(object.navigate_to);
    length += _getByteLength(object.initial_localization_waypoint);
    return length + 13;
  }

  static datatype() {
    // Returns string type for a message object
    return 'spot_msgs/NavigateToGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f9af434c1c55a1da6434e77de4087aaf';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string upload_path # Absolute path to map_directory, which is downloaded from tablet controller
    string navigate_to # Waypoint id string for where to go
    bool initial_localization_fiducial   # Tells the initializer whether to use fiducials
    string initial_localization_waypoint # Waypoint id to trigger localization 
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavigateToGoal(null);
    if (msg.upload_path !== undefined) {
      resolved.upload_path = msg.upload_path;
    }
    else {
      resolved.upload_path = ''
    }

    if (msg.navigate_to !== undefined) {
      resolved.navigate_to = msg.navigate_to;
    }
    else {
      resolved.navigate_to = ''
    }

    if (msg.initial_localization_fiducial !== undefined) {
      resolved.initial_localization_fiducial = msg.initial_localization_fiducial;
    }
    else {
      resolved.initial_localization_fiducial = false
    }

    if (msg.initial_localization_waypoint !== undefined) {
      resolved.initial_localization_waypoint = msg.initial_localization_waypoint;
    }
    else {
      resolved.initial_localization_waypoint = ''
    }

    return resolved;
    }
};

module.exports = NavigateToGoal;
