// Generated by gencpp from file odas_ros/OdasSsl.msg
// DO NOT EDIT!


#ifndef ODAS_ROS_MESSAGE_ODASSSL_H
#define ODAS_ROS_MESSAGE_ODASSSL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace odas_ros
{
template <class ContainerAllocator>
struct OdasSsl_
{
  typedef OdasSsl_<ContainerAllocator> Type;

  OdasSsl_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , E(0.0)  {
    }
  OdasSsl_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , E(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _E_type;
  _E_type E;





  typedef boost::shared_ptr< ::odas_ros::OdasSsl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odas_ros::OdasSsl_<ContainerAllocator> const> ConstPtr;

}; // struct OdasSsl_

typedef ::odas_ros::OdasSsl_<std::allocator<void> > OdasSsl;

typedef boost::shared_ptr< ::odas_ros::OdasSsl > OdasSslPtr;
typedef boost::shared_ptr< ::odas_ros::OdasSsl const> OdasSslConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odas_ros::OdasSsl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odas_ros::OdasSsl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::odas_ros::OdasSsl_<ContainerAllocator1> & lhs, const ::odas_ros::OdasSsl_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.E == rhs.E;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::odas_ros::OdasSsl_<ContainerAllocator1> & lhs, const ::odas_ros::OdasSsl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace odas_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::odas_ros::OdasSsl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odas_ros::OdasSsl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odas_ros::OdasSsl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odas_ros::OdasSsl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odas_ros::OdasSsl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odas_ros::OdasSsl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odas_ros::OdasSsl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da04e2eb0c067758372e166e0d3d06bb";
  }

  static const char* value(const ::odas_ros::OdasSsl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda04e2eb0c067758ULL;
  static const uint64_t static_value2 = 0x372e166e0d3d06bbULL;
};

template<class ContainerAllocator>
struct DataType< ::odas_ros::OdasSsl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odas_ros/OdasSsl";
  }

  static const char* value(const ::odas_ros::OdasSsl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odas_ros::OdasSsl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 E\n"
;
  }

  static const char* value(const ::odas_ros::OdasSsl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odas_ros::OdasSsl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.E);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdasSsl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odas_ros::OdasSsl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odas_ros::OdasSsl_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "E: ";
    Printer<double>::stream(s, indent + "  ", v.E);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODAS_ROS_MESSAGE_ODASSSL_H
