// Generated by gencpp from file spot_msgs/AprilTagState.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_APRILTAGSTATE_H
#define SPOT_MSGS_MESSAGE_APRILTAGSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace spot_msgs
{
template <class ContainerAllocator>
struct AprilTagState_
{
  typedef AprilTagState_<ContainerAllocator> Type;

  AprilTagState_()
    : header()
    , ids()
    , tag_ids()
    , names()  {
    }
  AprilTagState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ids(_alloc)
    , tag_ids(_alloc)
    , names(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _ids_type;
  _ids_type ids;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _tag_ids_type;
  _tag_ids_type tag_ids;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _names_type;
  _names_type names;





  typedef boost::shared_ptr< ::spot_msgs::AprilTagState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::AprilTagState_<ContainerAllocator> const> ConstPtr;

}; // struct AprilTagState_

typedef ::spot_msgs::AprilTagState_<std::allocator<void> > AprilTagState;

typedef boost::shared_ptr< ::spot_msgs::AprilTagState > AprilTagStatePtr;
typedef boost::shared_ptr< ::spot_msgs::AprilTagState const> AprilTagStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::AprilTagState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::AprilTagState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::AprilTagState_<ContainerAllocator1> & lhs, const ::spot_msgs::AprilTagState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ids == rhs.ids &&
    lhs.tag_ids == rhs.tag_ids &&
    lhs.names == rhs.names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::AprilTagState_<ContainerAllocator1> & lhs, const ::spot_msgs::AprilTagState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::AprilTagState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::AprilTagState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::AprilTagState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::AprilTagState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::AprilTagState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::AprilTagState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::AprilTagState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fcb386a7599f04b7e66974f6e2d0758";
  }

  static const char* value(const ::spot_msgs::AprilTagState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fcb386a7599f04bULL;
  static const uint64_t static_value2 = 0x7e66974f6e2d0758ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::AprilTagState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/AprilTagState";
  }

  static const char* value(const ::spot_msgs::AprilTagState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::AprilTagState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32[] ids\n"
"int32[] tag_ids\n"
"string[] names\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::spot_msgs::AprilTagState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::AprilTagState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ids);
      stream.next(m.tag_ids);
      stream.next(m.names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AprilTagState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::AprilTagState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::AprilTagState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "tag_ids[]" << std::endl;
    for (size_t i = 0; i < v.tag_ids.size(); ++i)
    {
      s << indent << "  tag_ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.tag_ids[i]);
    }
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_APRILTAGSTATE_H
