// Generated by gencpp from file spot_msgs/ClearBehaviorFault.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_CLEARBEHAVIORFAULT_H
#define SPOT_MSGS_MESSAGE_CLEARBEHAVIORFAULT_H

#include <ros/service_traits.h>


#include <spot_msgs/ClearBehaviorFaultRequest.h>
#include <spot_msgs/ClearBehaviorFaultResponse.h>


namespace spot_msgs
{

struct ClearBehaviorFault
{

typedef ClearBehaviorFaultRequest Request;
typedef ClearBehaviorFaultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearBehaviorFault
} // namespace spot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_msgs::ClearBehaviorFault > {
  static const char* value()
  {
    return "7cc61c4cb728bc0f5321bac4af610a6e";
  }

  static const char* value(const ::spot_msgs::ClearBehaviorFault&) { return value(); }
};

template<>
struct DataType< ::spot_msgs::ClearBehaviorFault > {
  static const char* value()
  {
    return "spot_msgs/ClearBehaviorFault";
  }

  static const char* value(const ::spot_msgs::ClearBehaviorFault&) { return value(); }
};


// service_traits::MD5Sum< ::spot_msgs::ClearBehaviorFaultRequest> should match
// service_traits::MD5Sum< ::spot_msgs::ClearBehaviorFault >
template<>
struct MD5Sum< ::spot_msgs::ClearBehaviorFaultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::ClearBehaviorFault >::value();
  }
  static const char* value(const ::spot_msgs::ClearBehaviorFaultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::ClearBehaviorFaultRequest> should match
// service_traits::DataType< ::spot_msgs::ClearBehaviorFault >
template<>
struct DataType< ::spot_msgs::ClearBehaviorFaultRequest>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::ClearBehaviorFault >::value();
  }
  static const char* value(const ::spot_msgs::ClearBehaviorFaultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_msgs::ClearBehaviorFaultResponse> should match
// service_traits::MD5Sum< ::spot_msgs::ClearBehaviorFault >
template<>
struct MD5Sum< ::spot_msgs::ClearBehaviorFaultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::ClearBehaviorFault >::value();
  }
  static const char* value(const ::spot_msgs::ClearBehaviorFaultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::ClearBehaviorFaultResponse> should match
// service_traits::DataType< ::spot_msgs::ClearBehaviorFault >
template<>
struct DataType< ::spot_msgs::ClearBehaviorFaultResponse>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::ClearBehaviorFault >::value();
  }
  static const char* value(const ::spot_msgs::ClearBehaviorFaultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_CLEARBEHAVIORFAULT_H
