// Generated by gencpp from file spot_msgs/MobilityParams.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_MOBILITYPARAMS_H
#define SPOT_MSGS_MESSAGE_MOBILITYPARAMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace spot_msgs
{
template <class ContainerAllocator>
struct MobilityParams_
{
  typedef MobilityParams_<ContainerAllocator> Type;

  MobilityParams_()
    : body_control()
    , locomotion_hint(0)
    , stair_hint(false)  {
    }
  MobilityParams_(const ContainerAllocator& _alloc)
    : body_control(_alloc)
    , locomotion_hint(0)
    , stair_hint(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _body_control_type;
  _body_control_type body_control;

   typedef uint32_t _locomotion_hint_type;
  _locomotion_hint_type locomotion_hint;

   typedef uint8_t _stair_hint_type;
  _stair_hint_type stair_hint;





  typedef boost::shared_ptr< ::spot_msgs::MobilityParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::MobilityParams_<ContainerAllocator> const> ConstPtr;

}; // struct MobilityParams_

typedef ::spot_msgs::MobilityParams_<std::allocator<void> > MobilityParams;

typedef boost::shared_ptr< ::spot_msgs::MobilityParams > MobilityParamsPtr;
typedef boost::shared_ptr< ::spot_msgs::MobilityParams const> MobilityParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::MobilityParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::MobilityParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::MobilityParams_<ContainerAllocator1> & lhs, const ::spot_msgs::MobilityParams_<ContainerAllocator2> & rhs)
{
  return lhs.body_control == rhs.body_control &&
    lhs.locomotion_hint == rhs.locomotion_hint &&
    lhs.stair_hint == rhs.stair_hint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::MobilityParams_<ContainerAllocator1> & lhs, const ::spot_msgs::MobilityParams_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::MobilityParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::MobilityParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::MobilityParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::MobilityParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::MobilityParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::MobilityParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::MobilityParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87bda7c4fbd2a6b19bdc029effa9f715";
  }

  static const char* value(const ::spot_msgs::MobilityParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87bda7c4fbd2a6b1ULL;
  static const uint64_t static_value2 = 0x9bdc029effa9f715ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::MobilityParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/MobilityParams";
  }

  static const char* value(const ::spot_msgs::MobilityParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::MobilityParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose body_control\n"
"uint32 locomotion_hint\n"
"bool stair_hint\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::spot_msgs::MobilityParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::MobilityParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.body_control);
      stream.next(m.locomotion_hint);
      stream.next(m.stair_hint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MobilityParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::MobilityParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::MobilityParams_<ContainerAllocator>& v)
  {
    s << indent << "body_control: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.body_control);
    s << indent << "locomotion_hint: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.locomotion_hint);
    s << indent << "stair_hint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stair_hint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_MOBILITYPARAMS_H
