// Generated by gencpp from file spot_msgs/NavigateToFeedback.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_NAVIGATETOFEEDBACK_H
#define SPOT_MSGS_MESSAGE_NAVIGATETOFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spot_msgs
{
template <class ContainerAllocator>
struct NavigateToFeedback_
{
  typedef NavigateToFeedback_<ContainerAllocator> Type;

  NavigateToFeedback_()
    : waypoint_id()  {
    }
  NavigateToFeedback_(const ContainerAllocator& _alloc)
    : waypoint_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _waypoint_id_type;
  _waypoint_id_type waypoint_id;





  typedef boost::shared_ptr< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateToFeedback_

typedef ::spot_msgs::NavigateToFeedback_<std::allocator<void> > NavigateToFeedback;

typedef boost::shared_ptr< ::spot_msgs::NavigateToFeedback > NavigateToFeedbackPtr;
typedef boost::shared_ptr< ::spot_msgs::NavigateToFeedback const> NavigateToFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::NavigateToFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::NavigateToFeedback_<ContainerAllocator1> & lhs, const ::spot_msgs::NavigateToFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.waypoint_id == rhs.waypoint_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::NavigateToFeedback_<ContainerAllocator1> & lhs, const ::spot_msgs::NavigateToFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f75af03a87882f1d13eb0cd853de33a";
  }

  static const char* value(const ::spot_msgs::NavigateToFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f75af03a87882f1ULL;
  static const uint64_t static_value2 = 0xd13eb0cd853de33aULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/NavigateToFeedback";
  }

  static const char* value(const ::spot_msgs::NavigateToFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string waypoint_id\n"
"\n"
"\n"
;
  }

  static const char* value(const ::spot_msgs::NavigateToFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoint_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateToFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::NavigateToFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::NavigateToFeedback_<ContainerAllocator>& v)
  {
    s << indent << "waypoint_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.waypoint_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_NAVIGATETOFEEDBACK_H
