// Generated by gencpp from file spot_msgs/SetVelocity.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_SETVELOCITY_H
#define SPOT_MSGS_MESSAGE_SETVELOCITY_H

#include <ros/service_traits.h>


#include <spot_msgs/SetVelocityRequest.h>
#include <spot_msgs/SetVelocityResponse.h>


namespace spot_msgs
{

struct SetVelocity
{

typedef SetVelocityRequest Request;
typedef SetVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocity
} // namespace spot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_msgs::SetVelocity > {
  static const char* value()
  {
    return "b42f41ffa01f8de6dcbf642f589646a1";
  }

  static const char* value(const ::spot_msgs::SetVelocity&) { return value(); }
};

template<>
struct DataType< ::spot_msgs::SetVelocity > {
  static const char* value()
  {
    return "spot_msgs/SetVelocity";
  }

  static const char* value(const ::spot_msgs::SetVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::spot_msgs::SetVelocityRequest> should match
// service_traits::MD5Sum< ::spot_msgs::SetVelocity >
template<>
struct MD5Sum< ::spot_msgs::SetVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::SetVelocity >::value();
  }
  static const char* value(const ::spot_msgs::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::SetVelocityRequest> should match
// service_traits::DataType< ::spot_msgs::SetVelocity >
template<>
struct DataType< ::spot_msgs::SetVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::SetVelocity >::value();
  }
  static const char* value(const ::spot_msgs::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_msgs::SetVelocityResponse> should match
// service_traits::MD5Sum< ::spot_msgs::SetVelocity >
template<>
struct MD5Sum< ::spot_msgs::SetVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_msgs::SetVelocity >::value();
  }
  static const char* value(const ::spot_msgs::SetVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_msgs::SetVelocityResponse> should match
// service_traits::DataType< ::spot_msgs::SetVelocity >
template<>
struct DataType< ::spot_msgs::SetVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::spot_msgs::SetVelocity >::value();
  }
  static const char* value(const ::spot_msgs::SetVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_SETVELOCITY_H
