// Generated by gencpp from file spot_msgs/SetVelocityRequest.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_SETVELOCITYREQUEST_H
#define SPOT_MSGS_MESSAGE_SETVELOCITYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace spot_msgs
{
template <class ContainerAllocator>
struct SetVelocityRequest_
{
  typedef SetVelocityRequest_<ContainerAllocator> Type;

  SetVelocityRequest_()
    : velocity_limit()  {
    }
  SetVelocityRequest_(const ContainerAllocator& _alloc)
    : velocity_limit(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _velocity_limit_type;
  _velocity_limit_type velocity_limit;





  typedef boost::shared_ptr< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelocityRequest_

typedef ::spot_msgs::SetVelocityRequest_<std::allocator<void> > SetVelocityRequest;

typedef boost::shared_ptr< ::spot_msgs::SetVelocityRequest > SetVelocityRequestPtr;
typedef boost::shared_ptr< ::spot_msgs::SetVelocityRequest const> SetVelocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::SetVelocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::SetVelocityRequest_<ContainerAllocator1> & lhs, const ::spot_msgs::SetVelocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.velocity_limit == rhs.velocity_limit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::SetVelocityRequest_<ContainerAllocator1> & lhs, const ::spot_msgs::SetVelocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b99f0d9a66914501fbc803f7ad9abee";
  }

  static const char* value(const ::spot_msgs::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b99f0d9a6691450ULL;
  static const uint64_t static_value2 = 0x1fbc803f7ad9abeeULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/SetVelocityRequest";
  }

  static const char* value(const ::spot_msgs::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The api only takes into account x and y for linear velocity, and z for angular.\n"
"# Other values are ignored.\n"
"geometry_msgs/Twist velocity_limit\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::spot_msgs::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity_limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::SetVelocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::SetVelocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "velocity_limit: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_limit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_SETVELOCITYREQUEST_H
